### ISSUE TITLE
Content checklist

### ISSUE THREAD

**Issue by cbahlai** [zipkinlab/zipkinlab.github.io#3]
Hi all! It looks like things are started to get populated. I have a content wishlist, though.

If you want to attempt adding this all in yourself, please don't hesitate! If you'd like me to get things a bit more templated out before you try, no prob- email me the content.

Here's my wishlist:

Sam:
- [x] I need your github username so I can add you to the organization
- [x] add a link to sam's user account in the dynamic N paper
- [x] Data from Dynamic N
- [x] Code from Dynamic N
- [x] the prettiest figure from Dynamic N to thumbnail on the webpage

@saund123 

from your currently in-review paper:
- [ ] title, abstract, working citation info
- [ ] code
- [ ] data (if available)

@ezipkin 
- [x] information about the combo model paper that's in review
- [x] code, data if available for the structured population models paper

@Grace89 
- [ ] as much information as you can provide about your unmarked population disease model study in prep

All:
- [ ] content for the isotopic ellipsoid section
- [ ] blurb describing the isotopic ellipsoid project
- [ ] blurb describing the work with unmarked population models
- [ ] check for typoes

**Comment by cbahlai** [comment]
Coing to close and update with  new list of needs for the website
