### ISSUE TITLE
Todo list for August website update

### ISSUE THREAD

**Issue by cbahlai** [zipkinlab/zipkinlab.github.io#5]
A comprehensive list of pending website updates!

- [x] Link to code for @saund123 Ecography paper
- [x] Link to code for @saund123  Piping plover IPM paper
- [x] once available, fleshing out of Timberdoodle project @lxwrght @Xuletajr @samrossman @saund123 @farrmt @asussman52 
- [ ] N occ model repo updated to include data @samrossman 
- [x] choose thumbnail for N occ model, add to website @samrossman 
- [ ] @farrmt 's distance sampling carnivore model, all info into organizational repos
- [x] add @farrmt 's distance sampling to website
- [ ] @asussman52  's hotspot model, all info into organizational repos
- [ ] add @asussman52  's hotspot model to website
- [x] @ezipkin 's paper with Jedidiah - code up, send @cbahlai info
- [x] @ezipkin create code repo for early community models (basic examples)
- [x] add project description for @ezipkin early community models to website
- [x] add @ezipkin paper to website
- [ ] @Xuletajr amphibian code, data, other info up in organizational repo
- [ ] put @Xuletajr 's project on website
- [ ] code for @samrossman 's ellipsoid project up in organizational repo
- [ ] add link to code for @samrossman ellipsoid paper
- [ ] update info for @cbahlai regime shift project

**Comment by ezipkin** [comment]
Hi guys - Check out the repo that I put up on the integrated count and detection-nondetection model: https://github.com/zipkinlab/Integrated_Count_Occupancy_model-Zipkin-et-al.-Ecology-2017 for an example on what to include in the README file.

**Comment by cbahlai** [comment]
- [x] add link to code for Brodie paper
- [x] thumbnail for hierarchical community models?
